<a href="https://colab.research.google.com/github/manuelavasquezo/Trabajos-IA-/blob/main/Taller_importaci%C3%B3n_Dana_Mendoza_Manuela_Vasquez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller importación y extracción de datos

**Nombres estudiantes:**

- Manuela Vásquez Osorio
- Dana Melissa Mendoza Santiago

In [118]:
import numpy as np
import pandas as pd
import os

1. Buscar la base de países del World Economic Outlook (WEO) del FMI, subirla a su drive y cargarla en el notebook concectándose a google drive

In [119]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [120]:
path = '/content/drive/MyDrive'
os.chdir(path)

In [121]:
weo = '/content/drive/MyDrive/datasets/weoapr2025all.xlsx'

In [122]:
#Primeras 5 filas
df = pd.read_excel(weo)
df.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,032.712","1,056.123",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,-6240,2267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,283.442","1,350.910",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,14501,17248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,86149,91272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0

In [123]:
#Últimas 10 filas
df.tail(10)

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
8616,698,ZWE,GGXONLB_NGDP,Zimbabwe,General government primary net lending/borrowing,Primary net lending/borrowing is net lending (...,Percent of GDP,Units,See notes for: General government primary net...,NaN,...,-4695,-5198,-1096,0.537,1529,1948,2028,2108,2108,2024.0
8617,698,ZWE,GGXWDN,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,National currency,Billions,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,698,ZWE,GGXWDN_NGDP,Zimbabwe,General government net debt,Net debt is calculated as gross debt minus fin...,Percent of GDP,Units,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8619,698,ZWE,GGXWDG,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,4935,51682,557793,673344,739670,786902,862793,930773,993329,2024.0
8620,698,ZWE,GGXWDG_NGDP,Zimbabwe,General government gross debt,Gross debt consists of all liabilities that re...,Percent of GDP,Units,See notes for: General government gross debt ...,NaN,...,99536,96586,94587,58568,56051,53294,52315,50485,48312,2024.0
8621,698,ZWE,NGDP_FY,Zimbabwe,Gross domestic product corresponding to fiscal...,Gross domestic product corresponding to fiscal...,National currency,Billions,Source: Ministry of Finance or Treasury Latest...,NaN,...,4958,53509,589716,"1,149.685","1,319.643","1,476.529","1,649.212","1,843.656","2,056.061",2024.0
8622,698,ZWE,BCA,Zimbabwe,Current account balance,Current account is all transactions other than...,U.S. dollars,Billions,Source: Reserve Bank of Zimbabwe and Ministry ...,-0.301,...,0.305,0.135,0.505,1143,1210,1198,1226,1120,0.996,2023.0
8623,698,ZWE,BCA_NGDPD,Zimbabwe,Current account balance,Current account is all transactions other than...,Percent of GDP,Units,"See notes for: Gross domestic product, curren...",NaN,...,0.935,0.384,1435,2994,3063,2927,2895,2554,2196,2023.0
8624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8625,"International Monetary Fund, World Economic Ou...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
#3 Filas aleatorias
df.sample(3)

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
6602,942,SRB,NGDP,Serbia,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office. Statistica...,NaN,...,"7,458.762","8,817.763","9,638.519","10,403.702","11,241.729","12,163.412","12,987.551","13,922.349","14,918.730",2024.0
7082,184,ESP,BCA,Spain,Current account balance,Current account is all transactions other than...,U.S. dollars,Billions,Source: Central Bank Latest actual data: 2024 ...,-5300,...,5072,43022,52086,43536,42047,39420,34778,30953,27550,2024.0
5457,196,NZL,NGDP_RPCH,New Zealand,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",1009,...,2856,1811,-0.483,1372,2722,2653,2281,2238,2196,2024.0

In [125]:
#Muestre de la fila 2 a la 5 y solamente la segunda columna
df.iloc[1:5, 1]

1    AFG
2    AFG
3    AFG
4    AFG
Name: ISO, dtype: object

In [126]:
#Use len() para saber cuántas filas tiene
len(df)

8626

In [127]:
#Use .shape para saber el número de filas y columnas
df.shape

(8626, 61)

In [128]:
#Use .columns para ver el nombre de las columnas
df.columns

Index([             'WEO Country Code',                           'ISO',
                    'WEO Subject Code',                       'Country',
                  'Subject Descriptor',                 'Subject Notes',
                               'Units',                         'Scale',
       'Country/Series-specific Notes',                            1980,
                                  1981,                            1982,
                                  1983,                            1984,
                                  1985,                            1986,
                                  1987,                            1988,
                                  1989,                            1990,
                                  1991,                            1992,
                                  1993,                            1994,
                                  1995,                            1996,
                                  1997,                            1998,
                                  1999,                            2000,
                                  2001,                            2002,
                                  2003,                            2004,
                                  2005,                            2006,
                                  2007,                            2008,
                                  2009,                            2010,
                                  2011,                            2012,
                                  2013,                            2014,
                                  2015,                            2016,
                                  2017,                            2018,
                                  2019,                            2020,
                                  2021,                            2022,
                                  2023,                            2024,
                                  2025,                            2026,
                                  2027,                            2028,
                                  2029,                            2030,
               'Estimates Start After'],
      dtype='object')

In [129]:
#Use .dtypes para saber el tipo de dato de cada columna
df.dtypes

WEO Country Code          object
ISO                       object
WEO Subject Code          object
Country                   object
Subject Descriptor        object
                          ...
2027                      object
2028                      object
2029                      object
2030                      object
Estimates Start After    float64
Length: 61, dtype: object

In [130]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 61 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   WEO Country Code               8625 non-null   object
 1   ISO                            8624 non-null   object
 2   WEO Subject Code               8624 non-null   object
 3   Country                        8624 non-null   object
 4   Subject Descriptor             8624 non-null   object
 5   Subject Notes                  8624 non-null   object
 6   Units                          8624 non-null   object
 7   Scale                          8624 non-null   object
 8   Country/Series-specific Notes  7648 non-null   object
 9   1980                           3861 non-null   object
 10  1981                           3995 non-null   object
 11  1982                           4039 non-null   object
 12  1983                           4079 non-null   object
 13  1984                           4104 non-null   object
 14  1985                           4187 non-null   object
 15  1986                           4235 non-null   object
 16  1987                           4259 non-null   object
 17  1988                           4348 non-null   object
 18  1989                           4409 non-null   object
 19  1990                           4889 non-null   object
 20  1991                           5049 non-null   object
 21  1992                           5435 non-null   object
 22  1993                           5635 non-null   object
 23  1994                           5762 non-null   object
 24  1995                           6108 non-null   object
 25  1996                           6242 non-null   object
 26  1997                           6404 non-null   object
 27  1998                           6565 non-null   object
 28  1999                           6659 non-null   object
 29  2000                           7086 non-null   object
 30  2001                           7236 non-null   object
 31  2002                           7329 non-null   object
 32  2003                           7357 non-null   object
 33  2004                           7427 non-null   object
 34  2005                           7460 non-null   object
 35  2006                           7467 non-null   object
 36  2007                           7469 non-null   object
 37  2008                           7478 non-null   object
 38  2009                           7499 non-null   object
 39  2010                           7512 non-null   object
 40  2011                           7517 non-null   object
 41  2012                           7536 non-null   object
 42  2013                           7554 non-null   object
 43  2014                           7578 non-null   object
 44  2015                           7592 non-null   object
 45  2016                           7594 non-null   object
 46  2017                           7599 non-null   object
 47  2018                           7597 non-null   object
 48  2019                           7597 non-null   object
 49  2020                           7560 non-null   object
 50  2021                           7560 non-null   object
 51  2022                           7560 non-null   object
 52  2023                           7557 non-null   object
 53  2024                           7485 non-null   object
 54  2025                           7371 non-null   object
 55  2026                           7371 non-null   object
 56  2027                           7246 non-null   object
 57  2028                           7246 non-null   object
 58  2029                           7246 non-null   object
 59  2030                           7246 non-null   object
 60  Estimates Start After          7648 non-null   float64
dtypes: float64(1), object(60)
memory usage: 4.0+ MB

2. Conectarse a la API del Banco Mundial y traer datos de inflación para Colombia, Ecuador, Brasil, Chile, Mexico y Perú, años 2010-2023

In [131]:
!pip install wbdata

Requirement already satisfied: wbdata in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [132]:
import wbdata
import datetime
!pip install wbdata --upgrade

Requirement already satisfied: wbdata in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [133]:
wbdata.get_indicators(query="inflation", source=2)

id                    name
--------------------  -------------------------------------------------
FP.CPI.TOTL.ZG        Inflation, consumer prices (annual %)
NY.GDP.DEFL.KD.ZG     Inflation, GDP deflator (annual %)
NY.GDP.DEFL.KD.ZG.AD  Inflation, GDP deflator: linked series (annual %)

In [134]:
indicador = {"FP.CPI.TOTL.ZG": "Inflación"}

# El orden es: año (2010), mes (1), día (1)
fecha_inicio = datetime.datetime(2010, 1, 1)
# El orden es: año (2023), mes (1), día (1)
fecha_fin = datetime.datetime(2023, 1, 1)

# Descargar datos
df1 = wbdata.get_dataframe(indicador, country= ["COL","ECU","BRA","CHL","MEX","PER"], date=(fecha_inicio, fecha_fin))

df1

              Inflación
country date
Brazil  2023   4.593563
        2022   9.280106
        2021   8.301660
        2020   3.211768
        2019   3.732976
...                 ...
Peru    2014   3.411946
        2013   2.767897
        2012   3.611213
        2011   3.369311
        2010   1.528321

[84 rows x 1 columns]

In [135]:
#Primeras 5 filas
df1.head()

              Inflación
country date
Brazil  2023   4.593563
        2022   9.280106
        2021   8.301660
        2020   3.211768
        2019   3.732976

In [136]:
#Últimas 10 filas
df1.tail(10)

              Inflación
country date
Peru    2019   2.252122
        2018   1.509154
        2017   2.994900
        2016   3.557177
        2015   3.398092
        2014   3.411946
        2013   2.767897
        2012   3.611213
        2011   3.369311
        2010   1.528321

In [137]:
#3 Filas aleatorias
df1.sample(3)

              Inflación
country date
Brazil  2015   9.029901
Ecuador 2016   1.728265
Peru    2023   6.455613

In [183]:
#Muestre de la fila 2 a la 5 y solamente la segunda columna
df1.iloc[1:5, 0]
#El df solo tiene una columna, lo podemos ver con .shape, es por esto que se usa 0 para mostrar la única que hay. Si se intenta mostrar la segunda columa arroja un error

country  date
Brazil   2022    9.280106
         2021    8.301660
         2020    3.211768
         2019    3.732976
Name: Inflación, dtype: float64

In [142]:
#Use len() para saber cuantas filas tiene
len(df1)

84

In [143]:
#Use .shape para saber el número de filas y columnas
df1.shape

(84, 1)

In [144]:
#Use .columns para ver el nombre de las columnas
df1.columns

Index(['Inflación'], dtype='object')

In [147]:
#Use dtypes para saver el tipo de dato de cada columna
df1.dtypes

Inflación    float64
dtype: object

In [148]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df1.info()

<class 'wbdata.client.DataFrame'>
MultiIndex: 84 entries, ('Brazil', '2023') to ('Peru', '2010')
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Inflación  84 non-null     float64
dtypes: float64(1)
memory usage: 1.8+ KB

3. Conectarse a la API del Banco Mundial y traer los siguientes datos para Alemania 2010-2023: crecimiento del PIB, PIB per cápita, tasa de inflación, tasa de desempleo y población.

In [149]:
indicador = {"NY.GDP.MKTP.KD.ZG": "Crecimiento del PIB","NY.GDP.PCAP.PP.CD": "PIB per cápita en PPA","FP.CPI.TOTL.ZG": "Tasa de inflación", "SL.UEM.TOTL.ZS":"Desempleo","SP.POP.TOTL":"Población"}

# El orden es: año (2010), mes (1), día (1)
fecha_inicio = datetime.datetime(2010, 1, 1)
# El orden es: año (2023), mes (1), día (1)
fecha_fin = datetime.datetime(2023, 1, 1)

# Descargar datos
df2 = wbdata.get_dataframe(indicador, country= ["DEU"], date=(fecha_inicio, fecha_fin))

df2

,Crecimiento del PIB,PIB per cápita en PPA,Tasa de inflación,Desempleo,Población
date,,,,,
2023,-0.869648,71684.031188,5.946437,3.071,83287273.0
2022,1.809258,69048.988404,6.872574,3.137,83177813.0
2021,3.910000,62530.765320,3.066667,3.594,83196078.0
2020,-4.131914,58685.872700,0.144878,3.881,83160871.0
2019,0.977735,59270.727650,1.445660,3.163,83092962.0
2018,1.135696,56273.040563,1.732169,3.384,82905782.0
2017,2.797907,54110.253665,1.509495,3.781,82657002.0
2016,2.222222,51569.901684,0.491747,4.104,82348669.0
2015,1.663006,48545.400722,0.514426,4.612,81686611.0
2014,2.180186,47938.796821,0.906794,4.979,80982500.0
2013,0.396996,45889.017302,1.504723,5.316,80645605.0
2012,0.463512,44229.394192,2.008489,5.372,80425823.0
2011,3.757969,43398.344399,2.075173,5.967,80274983.0
2010,4.134638,39726.098692,1.103810,7.043,81776930.0

In [150]:
#Primeras 5 filas
df2.head()

,Crecimiento del PIB,PIB per cápita en PPA,Tasa de inflación,Desempleo,Población
date,,,,,
2023,-0.869648,71684.031188,5.946437,3.071,83287273.0
2022,1.809258,69048.988404,6.872574,3.137,83177813.0
2021,3.910000,62530.765320,3.066667,3.594,83196078.0
2020,-4.131914,58685.872700,0.144878,3.881,83160871.0
2019,0.977735,59270.727650,1.445660,3.163,83092962.0

In [151]:
#Últimas 10 filas
df2.tail(10)

,Crecimiento del PIB,PIB per cápita en PPA,Tasa de inflación,Desempleo,Población
date,,,,,
2019,0.977735,59270.727650,1.445660,3.163,83092962.0
2018,1.135696,56273.040563,1.732169,3.384,82905782.0
2017,2.797907,54110.253665,1.509495,3.781,82657002.0
2016,2.222222,51569.901684,0.491747,4.104,82348669.0
2015,1.663006,48545.400722,0.514426,4.612,81686611.0
2014,2.180186,47938.796821,0.906794,4.979,80982500.0
2013,0.396996,45889.017302,1.504723,5.316,80645605.0
2012,0.463512,44229.394192,2.008489,5.372,80425823.0
2011,3.757969,43398.344399,2.075173,5.967,80274983.0
2010,4.134638,39726.098692,1.103810,7.043,81776930.0

In [152]:
#3 filas aleatorias
df2.sample(3)

,Crecimiento del PIB,PIB per cápita en PPA,Tasa de inflación,Desempleo,Población
date,,,,,
2011,3.757969,43398.344399,2.075173,5.967,80274983.0
2013,0.396996,45889.017302,1.504723,5.316,80645605.0
2022,1.809258,69048.988404,6.872574,3.137,83177813.0

In [153]:
#Muestre la fila 2 a la 5 y solamente la segunda columna
df2.iloc[1:5, 1]

date
2022    69048.988404
2021    62530.765320
2020    58685.872700
2019    59270.727650
Name: PIB per cápita en PPA, dtype: float64

In [154]:
#Use .len() para saber cuantas filas tiene
len(df2)

14

In [155]:
#Use .shape para saber el numero de filas y columnas
df2.shape

(14, 5)

In [156]:
#Use .columns para ver el nombre de las columnas
df2.columns

Index(['Crecimiento del PIB', 'PIB per cápita en PPA', 'Tasa de inflación',
       'Desempleo', 'Población'],
      dtype='object')

In [158]:
#Use .dtypes para saber el tipo de dato de cada columna
df2.dtypes

Crecimiento del PIB      float64
PIB per cápita en PPA    float64
Tasa de inflación        float64
Desempleo                float64
Población                float64
dtype: object

In [159]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df2.info()

<class 'wbdata.client.DataFrame'>
Index: 14 entries, 2023 to 2010
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crecimiento del PIB    14 non-null     float64
 1   PIB per cápita en PPA  14 non-null     float64
 2   Tasa de inflación      14 non-null     float64
 3   Desempleo              14 non-null     float64
 4   Población              14 non-null     float64
dtypes: float64(5)
memory usage: 672.0+ bytes

4. Traer dos conjuntos de datos de la página de datos abiertos del Gobierno de Colombia usando API. Los que le llamen la atención

In [160]:
import requests

In [184]:
url = "https://www.datos.gov.co/resource/2a76-5evx.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df3 = pd.DataFrame(data)

df3.head()

    ano cod_etc    nombre_etc
0  2021    3819  Buenaventura
1  2020    3819  Buenaventura
2  2019    3819  Buenaventura
3  2018    3819  Buenaventura
4  2017    3819  Buenaventura

In [185]:
#Primeras 5 filas
df3.head()

    ano cod_etc    nombre_etc
0  2021    3819  Buenaventura
1  2020    3819  Buenaventura
2  2019    3819  Buenaventura
3  2018    3819  Buenaventura
4  2017    3819  Buenaventura

In [186]:
#Últimas 10 filas
df3.tail(10)

     ano cod_etc    nombre_etc
4   2017    3819  Buenaventura
5   2016    3819  Buenaventura
6   2015    3819  Buenaventura
7   2014    3819  Buenaventura
8   2013    3819  Buenaventura
9   2012    3819  Buenaventura
10  2011    3819  Buenaventura
11  2022    3819  Buenaventura
12  2023    3819  Buenaventura
13  2024    3819  Buenaventura

In [187]:
#3 filas aleatorias
df3.sample(3)

     ano cod_etc    nombre_etc
2   2019    3819  Buenaventura
10  2011    3819  Buenaventura
13  2024    3819  Buenaventura

In [188]:
#Muestre la fila 2 a la 5 y solamente la segunda columna
df3.iloc[2:6,1]

2    3819
3    3819
4    3819
5    3819
Name: cod_etc, dtype: object

In [189]:
#Use .len() para saber cuantas filas tiene
len(df3)

14

In [190]:
#Use .shape para saber el numero de filas y columnas
df3.shape

(14, 3)

In [191]:
#Use .columns para ver el nombre de las columnas
df3.columns

Index(['ano', 'cod_etc', 'nombre_etc'], dtype='object')

In [192]:
#Use .dtypes para saber el tipo de dato de cada columna
df3.dtypes

ano           object
cod_etc       object
nombre_etc    object
dtype: object

In [193]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ano         14 non-null     object
 1   cod_etc     14 non-null     object
 2   nombre_etc  14 non-null     object
dtypes: object(3)
memory usage: 468.0+ bytes

In [162]:
url = "https://www.datos.gov.co/resource/6z97-i2yt.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df4 = pd.DataFrame(data)

df4.head()

,vigencia,mes,rubro,concepto,presupuesto_vigente_pv,recaudos_rs,rs_pv
0,2025,7,0,DISPONIBILIDAD INICIAL,254497000000,160598462957,6310.0
1,2025,7,1-02-5-01-03-05-4,PRODUCTOS QUÍMICOS N.C.P.,773998900000,287869623233,3719.00
2,2025,7,1-02-5-01-04-01-2,PRODUCTOS DE HIERRO Y ACERO,5824000000,2011507282,3454.00
3,2025,7,1-02-5-01-04-04-7,ARMAS Y MUNICIONES Y SUS PARTES Y PIEZAS,246663000000,107113202118,4342.00
4,2025,7,1-02-5-01-05-04-6,SERVICIOS DE INSTALACIONES,1407000000,137499,1.00

In [174]:
#Primeras 5 filas
df4.head()

,vigencia,mes,rubro,concepto,presupuesto_vigente_pv,recaudos_rs,rs_pv
0,2025,7,0,DISPONIBILIDAD INICIAL,254497000000,160598462957,6310.0
1,2025,7,1-02-5-01-03-05-4,PRODUCTOS QUÍMICOS N.C.P.,773998900000,287869623233,3719.00
2,2025,7,1-02-5-01-04-01-2,PRODUCTOS DE HIERRO Y ACERO,5824000000,2011507282,3454.00
3,2025,7,1-02-5-01-04-04-7,ARMAS Y MUNICIONES Y SUS PARTES Y PIEZAS,246663000000,107113202118,4342.00
4,2025,7,1-02-5-01-05-04-6,SERVICIOS DE INSTALACIONES,1407000000,137499,1.00

In [175]:
#Últimas 10 filas
df4.tail(10)

,vigencia,mes,rubro,concepto,presupuesto_vigente_pv,recaudos_rs,rs_pv
38,2025,11,2-05-1-03,VALORES DISTINTOS A ACCIONES,20000000000,28734528549,14367.00
39,2025,11,2-15-1-03,DE OTRAS EMPRESAS,6978200000,6723724786,9635.00
40,2025,12,0,DISPONIBILIDAD INICIAL,254497000000,160598462957,6310.0
41,2025,12,1-02-5-01-03-05-4,PRODUCTOS QUÍMICOS N.C.P.,773998900000,606586600947,7837.00
42,2025,12,1-02-5-01-04-01-2,PRODUCTOS DE HIERRO Y ACERO,5824000000,4994245543,8575.00
43,2025,12,1-02-5-01-04-04-7,ARMAS Y MUNICIONES Y SUS PARTES Y PIEZAS,246663000000,134595048511,5457.00
44,2025,12,1-02-5-01-05-04-6,SERVICIOS DE INSTALACIONES,1407000000,283715,2.00
45,2025,12,1-02-5-01-08-08-9,OTROS SERVICIOS DE FABRICACIÓN,17710100000,21747260922,12280.0
46,2025,12,2-05-1-03,VALORES DISTINTOS A ACCIONES,20000000000,31621852985,15811.00
47,2025,12,2-15-1-03,DE OTRAS EMPRESAS,6978200000,7374001150,10567.00

In [176]:
#3 filas aleatorias
df4.sample(3)

,vigencia,mes,rubro,concepto,presupuesto_vigente_pv,recaudos_rs,rs_pv
10,2025,8,1-02-5-01-04-01-2,PRODUCTOS DE HIERRO Y ACERO,5824000000,4504884603,7735.00
40,2025,12,0,DISPONIBILIDAD INICIAL,254497000000,160598462957,6310.0
20,2025,9,1-02-5-01-05-04-6,SERVICIOS DE INSTALACIONES,1407000000,174233,1.00

In [177]:
#Muestre la fila 2 a la 5 y solamente la segunda columna
df4.iloc[2:6,1]

2    7
3    7
4    7
5    7
Name: mes, dtype: object

In [178]:
#Use .len() para saber cuantas filas tiene
len(df4)

48

In [179]:
#Use .shape para saber el numero de filas y columnas
df4.shape

(48, 7)

In [180]:
#Use .columns para ver el nombre de las columnas
df4.columns

Index(['vigencia', 'mes', 'rubro', 'concepto', 'presupuesto_vigente_pv',
       'recaudos_rs', 'rs_pv'],
      dtype='object')

In [181]:
#Use .dtypes para saber el tipo de dato de cada columna
df4.dtypes

vigencia                  object
mes                       object
rubro                     object
concepto                  object
presupuesto_vigente_pv    object
recaudos_rs               object
rs_pv                     object
dtype: object

In [182]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   vigencia                48 non-null     object
 1   mes                     48 non-null     object
 2   rubro                   48 non-null     object
 3   concepto                48 non-null     object
 4   presupuesto_vigente_pv  48 non-null     object
 5   recaudos_rs             48 non-null     object
 6   rs_pv                   48 non-null     object
dtypes: object(7)
memory usage: 2.8+ KB

5. Investigue otra página de donde pueda traer los datos mediante API y cargue el conjunto de datos en notebook

In [163]:
url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    'vs_currency': 'usd',
    'order': 'market_cap_desc',
    'per_page': 50,
    'page': 1
}

response = requests.get(url, params=params)
df5= pd.DataFrame(response.json())
df5

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,71180.000000,1425992334426,1,1425993404010,5.728301e+10,73476.000000,...,1.999835e+07,2.100000e+07,126080.000000,-43.54359,2025-10-06T18:57:42.558Z,6.781000e+01,1.048716e+05,2013-07-06T00:00:00.000Z,None,2026-03-05T21:53:34.541Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2080.550000,251453839190,2,251453839190,2.431761e+10,2162.460000,...,1.206921e+08,NaN,4946.050000,-57.93498,2025-08-24T19:21:03.333Z,4.329790e-01,4.804214e+05,2015-10-20T00:00:00.000Z,"{'times': 38.08404353073514, 'currency': 'btc'...",2026-03-05T21:53:37.266Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.000000,183911740439,3,189379070825,8.805857e+10,1.000000,...,1.893655e+11,NaN,1.320000,-24.41432,2018-07-24T00:00:00.000Z,5.725210e-01,7.467841e+01,2015-03-02T00:00:00.000Z,None,2026-03-05T21:53:35.550Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,648.000000,88438125292,4,88438125292,1.198932e+09,664.510000,...,1.363585e+08,2.000000e+08,1369.990000,-52.70029,2025-10-13T08:41:24.131Z,3.981770e-02,1.627322e+06,2017-10-19T00:00:00.000Z,None,2026-03-05T21:53:34.429Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.410000,85991929396,5,140741708202,2.787363e+09,1.450000,...,9.998571e+10,1.000000e+11,3.650000,-61.40524,2025-07-18T03:40:53.808Z,2.686210e-03,5.229027e+04,2014-05-22T00:00:00.000Z,None,2026-03-05T21:53:35.322Z
5,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999957,77097125092,6,77097125092,1.285918e+10,1.000000,...,7.710394e+10,NaN,1.170000,-14.73532,2019-05-08T00:40:28.300Z,8.776470e-01,1.393015e+01,2023-03-11T08:02:13.981Z,None,2026-03-05T21:53:35.457Z
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,89.140000,50815909788,7,55439125174,5.007450e+09,92.680000,...,6.217321e+08,NaN,293.310000,-69.60919,2025-01-19T11:15:27.957Z,5.008010e-01,1.769945e+04,2020-05-11T19:35:23.449Z,None,2026-03-05T21:53:35.310Z
7,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.284639,26968463652,8,26968501755,5.983028e+08,0.287968,...,9.474184e+10,NaN,0.431288,-34.00264,2024-12-04T00:10:40.323Z,1.804340e-03,1.567522e+04,2017-11-12T00:00:00.000Z,"{'times': 148.80996259187953, 'currency': 'usd...",2026-03-05T21:53:35.149Z
8,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.025000,15989600901,9,15989600901,2.551829e+07,1.034000,...,1.560276e+10,NaN,1.370000,-25.17592,2025-10-28T06:05:38.345Z,1.553570e-01,5.596391e+02,2025-10-31T14:27:24.456Z,None,2026-03-05T21:53:34.884Z
9,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,0.093984,14411899344,10,15889116393,1.620413e+09,0.102713,...,1.690000e+11,NaN,0.731578,-87.15324,2021-05-08T05:08:23.458Z,8.690000e-05,1.080473e+05,2015-05-06T00:00:00.000Z,None,2026-03-05T21:53:35.244Z
10,whitebit,wbt,WhiteBIT Coin,https://coin-images.coingecko.com/coins/images...,54.620000,11665193279,11,17482912427,1.001554e+08,55.910000,...,3.200447e+08,4.000000e+08,64.110000,-14.66464,2025-12-10T20:16:13.582Z,3.060000e+00,1.686752e+03,2023-02-13T19:01:21.899Z,None,2026-03-05T21:53:35.305Z
11,usds,usds,USDS,https://coin-images.coingecko.com/coins/images...,0.999978,10729890945,12,10735768503,1.393997e+07,1.001000,...,1.073608e+10,NaN,1.057000,-5.41993,2024-10-29T05:40:51.197Z,9.482650e-01,5.457430e+00,2024-10-03T13:19:28.826Z,None,2026-03-05T21:53:34.965Z
12,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,0.269455,9928244896,13,12131684853,5.841281e+08,0.281542,...,4.500000e+10,4.500000e+10,3.090000,-91.27105,2021-09-02T06:00:10.474Z,1.925275e-02,1.299566e+03,2020-03-13T02:22:55.044Z,None,2026-03-05T21:53:35.362Z
13,bitcoin-cash,bch,Bitcoin Cash,https://coin-images.coingecko.com/coins/images...,460.670000,9209579254,14,9209583570,2.956408e+08,471.150000,...,2.000324e+07,2.100000e+07,3785.820000,-87.83157,2017-12-20T00:00:00.000Z,7.693000e+01,4.987858e+02,2018-12-16T00:00:00.000Z,None,2026-03-05T21:53:35.140Z
14,leo-token,leo,LEO Token,https://coin-images.coingecko.com/coins/images...,9.000000,8289575644,15,8865726594,3.927803e+06,9.150000,...,9.852395e+08,NaN,10.140000,-11.25808,2025-03-10T09:26:43.294Z,7.998590e-01,1.024459e+03,2019-12-24T15:14:35.376Z,None,2026-03-05T21:53:34.917Z
15,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,30.670000,7316373083,16,29533512899,2.235193e+08,32.320000,...,9.622740e+08,1.000000e+09,59.300000,-48.28030,2025-09-18T03:30:30.650Z,3.810000e+00,7.052970e+02,2024-11-29T09:30:30.871Z,None,2026-03-05T21:53:35.907Z
16,monero,xmr,Monero,https://coin-images.coingecko.com/coins/images...,367.210000,6792735433,17,6792735433,1.379722e+08,375.040000,...,1.844674e+07,NaN,797.730000,-53.96786,2026-01-14T19:34:07.049Z,2.161770e-01,1.697677e+05,2015-01-14T00:00:00.000Z,None,2026-03-05T21:53:39.354Z
17,chainlink,link,Chainlink,https://coin-images.coingecko.com/coins/images...,9.230000,6540627010,18,9236869485,4.390242e+08,9.480000,...,1.000000e+09,1.000000e+09,52.700000,-82.48197,2021-05-10T00:13:57.214Z,1.481830e-01,6.129726e+03,2017-11-29T00:00:00.000Z,None,2026-03-05T21:53:35.402Z
18,ethena-usde,usde,Ethena USDe,https://coin-images.coingecko.com/coins/images...,0.999377,5966279850,19,5966279850,1.071923e+08,0.999917,...,5.970527e+09,NaN,1.034000,-3.36028,2025-12-09T17:10:12.652Z,9.294860e-01,7.508640e+00,2024-10-04T07:57:15.809Z,None,2026-03-05T21:53:35.460Z
19,canton-network,cc,Canton,https://coin-images.coingecko.com/coins/images...,0.150128,5699094867,20,5699094867,3.729649e+07,0.157991,...,3.795159e+10,NaN,0.194152,-22.64284,2026-02-03T08:02:08.411Z,5.902400e-02,1.544559e+02,2025-12-06T10:32:09.784Z,None,2026-03-05T21:53:34.990Z
20,stellar,xlm,Stellar,https://coin-images.coingecko.com/coins/images...,0.157379,5193297651,21,7872256462,1.070601e+08,0.162410,...,5.000179e+10,NaN,0.875563,-81.98520,2018-01-03T00:00:00.000Z,4.761200e-04,3.302815e+04,2015-03-05T00:00:00.000Z,None,2026-03-05T21:53:35.301Z
21,usd1-wlfi,usd1,USD1,https://coin-images.coingecko.com/coins/images...,0.999793,4608440982,22,4608440982,2.102567e+09,0.999991,...,4.610400e+09,NaN,1.025000,-2.47012,2025-05-12T12:36:39.412Z,9.896330e-01,9.982300e-01,2025-10-01T08:51:32.103Z,None,2026-03-05T21:53:35.255Z
22,rain,rain,Rain,https://coin-images.coingecko.com/coins/images...,0.009506,4557003709,23,10962051852,3.052849e+07,0.009655,...,1.149929e+12,1.150000e+12,0.010901,-12.56708,2026-02-09T16:50:09.904Z,2.221260e-03,3.290833e+02,2025-09-14T08:56:57.416Z,None,2026-03-05T21:53:34.973Z
23,hedera-hashgraph,hbar,Hedera,https://coin-images.coingecko.com/coins/images...,0.099750,4321194940,24,4989438228,9.447607e+07,0.102081,...,5.000000e+10,5.000000e+10,0.569229,-82.45101,2021-09-15T10:40:28.318Z,9.861110e-03,9.130086e+02,2020-01-02T17:30:24.852Z,None,2026-03-05T21:53:35.538Z
24,litecoin,ltc,Litecoin,https://coin-images.coingecko.com/coins/images...,55.750000,4289174886,25,4289226467,3.821243e+08,57.380000,...,7.691820e+07,8.400000e+07,410.260000,-86.39943,2021-05-10T03:13:07.904Z,1.150000e+00,4.756861e+03,2015-01-14T00:00:00.000Z,None,2026-03-05T21:53:35.423Z
25,paypal-usd,pyusd,PayPal USD,https://coin-images.coingecko.com/coins/images...,0.999950,4202697395,26,4202697395,8.611754e+07,1.001000,...,4.203027e+09,NaN,1.021000,-2.04519,2023-10-23T22:44:57.056Z,9.594260e-01,4.214520e+00,2024-12-05T22:31:13.430Z,None,2026-03-05T21:53:35.041Z
26,dai,dai,Dai,https://coin-images.coingecko.com/coins/images...,0.999728,4117944969,27,4117944969,6.895650e+07,1.001000,...,4.118603e+09,NaN,1.220000,-17.95615,2020-03-13T03:02:50.373Z,8.819600e-01,1.339037e+01,2023-03-11T07:50:50.514Z,None,2026-03-05T21:53:35.123Z
27,avalanche-2,avax,Avalanche,https://coin-images.coingecko.com/coins/images...,9.450000,4081407313,28,4380765558,2.856381e+08,9.590000,...,4.634411e+08,7.200000e+08,144.960000,-93.46894,2021-11-21T14:18:56.538Z,2.800000e+00,2.379966e+02,2020-12-31T13:15:21.540Z,None,2026-03-05T21:53:35.216Z
28,zcash,zec,Zcash,https://coin-images.coingecko.com/coins/images...,230.420000,3819446259,29,3819875182,3.169653e+08,249.430000,...,1.658693e+07,2.100000e+07,3191.930000,-92.78111,2016-10-29T00:00:00.000Z,1.608000e+01,1.332961e+03,2024-07-05T04:22:29.321Z,None,2026-03-05T21:53:35.077Z
29,sui,sui,Sui,https://coin-images.coingecko.com/coins/images...,0.957526,3736522816,30,9580865347,6.275985e+08,0.982803,...,1.000000e+10,1.000000e+10,5.350000,-82.09082,2025-01-04T22:56:18.063Z,3.648460e-01,1.624465e+02,2023-10-19T10:40:30.078Z,None,2026-03-05T21:53:38.300Z
30,the-open-network,ton,Toncoin,https://coin-images.coingecko.com/coins/images...,1.350000,3313036985,31,6963945433,1.180095e+08,1.390000,...,5.155919e+09,NaN,8.250000,-83.67984,2024-06-15T00:36:51.509Z,5.193640e-01,1.593561e+02,2021-09-21T00:33:11.092Z,None,2026-03-05T21:53:39.449Z
31,shiba-inu,shib,Shiba Inu,https://coin-images.coingecko.com/coins/images...,0.000006,3279265672,32,3280693381,1.287474e+08,0.000006,...,5.895003e+14,NaN,0.000086,-93.54239,2021-10-28T03:54:55.568Z,5.636600e-11,9.870671e+06,2020-11-28T11:26:25.838Z,None,2026-03-05T21:53:35.525Z
32,crypto-com-chain,cro,Cronos,https://coin-images.coingecko.com/coins/images...,0.077207,3172447772,33,7602650021,1.224927e+07,0.078157,...,9.844672e+10,1.000000e+11,0.965407,-91.99717,2021-11-24T15:53:54.855Z,1.211960e-02,5.374794e+02,2019-02-08T00:00:00.000Z,None,2026-03-05T21:53:35.064Z
33,tether-gold,xaut,Tether Gold,https://coin-images.coingecko.com/coins/images...,5055.690000,2853661762,34,3602770361,7.912108e+08,5153.200000,...,7.127471e+05,NaN,5596.700000,-9.67222,2026-01-29T06:25:57.628Z,1.447840e+03,2.491667e+02,2020-03-19T13:45:41.821Z,None,2026-03-05T21:53:35.219Z
34,world-liberty-financial,wlfi,World Liberty Financial,https://coin-images.coingecko.com/coins/images...,0.102126,2825656704,35,10215202344,1.247980e+08,0.108051,...,1.000000e+11,1.000000e+11,0.331336,-69.17740,2025-09-01T12:20:09.597Z,9.830800e-02,3.884340e+00,2026-02-08T17:02:14.734Z,None,2026-03-05T21:53:35.160Z
35,polkadot,dot,Polkadot,https://coin-images.coingecko.com/coins/images...,1.540000,2577466320,36,2577466320,1.632435e+08,1.550000,...,1.671637e+09,2.100000e+09,54.980000,-97.19499,2021-11-04T14:10:09.301Z,1.150000e+00,3.406651e+01,2026-02-06T00:25:45.413Z,None,2026-03-05T21:53:35.682Z
36,memecore,m,MemeCore,https://coin-images.coingecko.com/coins/images...,1.470000,2553200563,37,7827373146,8.008462e+06,1.490000,...,5.342765e+09,1.000000e+10,2.960000,-50.30558,2025-09-18T07:27:06.144Z,4.746135e-02,2.997984e+03,2025-07-04T03:56:17.448Z,None,2026-03-05T21:53:35.346Z
37,uniswap,uni,Uniswap,https://coin-images.coingecko.com/coins/images...,3.990000,2528718314,38,3585674938,2.339148e+08,4.080000,...,8.983784e+08,1.000000e+09,44.920000,-91.10966,2021-05-03T05:25:04.822Z,1.030000e+00,2.876412e+02,2020-09-17T01:20:38.214Z,None,2026-03-05T21:53:35.573Z
38,pax-gold,paxg,PAX Gold,https://coin-images.coingecko.com/coins/images...,5091.800000,2522830401,39,2522830401,4.293025e+08,5199.380000,...,4.954754e+05,NaN,5619.090000,-9.35756,2026-01-29T06:30:56.612Z,1.399640e+03,2.638990e+02,2019-11-18T03:09:35.959Z,None,2026-03-05T21:53:36.886Z
39,mantle,mnt,Mantle,https://coin-images.coingecko.com/coins/images...,0.700561,2296401087,40,4357013300,4.176472e+07,0.730463,...,6.219317e+09,6.219317e+09,2.860000,-75.47074,2025-10-09T01:04:46.659Z,3.079780e-01,1.273946e+02,2023-10-18T02:50:46.942Z,None,2026-03-05T21:53:36.065Z
40,blackrock-usd-institutional-digital-liquidity-...,buidl,BlackRock USD Institutional Digital Liquidity ...,https://coin-images.coingecko.com/coins/images...,1.000000,2009494196,41,2006635146,0.000000e+00,1.000000,...,2.006635e+09,NaN,1.000000,0.00000,2025-02-12T05:00:10.912Z,1.000000e+00,0.000000e+00,2025-02-12T05:45:10.196Z,None,2026-03-05T21:50:23.212Z
41,hashnote-usyc,usyc,Circle USYC,https://coin-images.coingecko.com/coins/images...,1.120000,1946565991,42,1946565991,5.593500e+04,1.120000,...,1.740028e+09,NaN,1.120000,-0.00027,2026-03-04T11:11:25.534Z,1.026000e+00,9.023990e+00,2024-12-05T22:31:20.475Z,None,2026-03-05T00:43:04.053Z
42,okb,okb,OKB,https://coin-images.coingecko.com/coins/images...,92.390000,1941874120,43,1941874120,3.497981e+08,117.600000,...,2.100000e+07,2.100000e+07,255.500000,-64.06221,2025-08-22T01:50:26.131Z,5.806080e-01,1.571478e+04,2019-01-14T00:00:00.000Z,None,2026-03-05T21:53:38.102Z
43,pi-network,pi,Pi Network,https://coin-images.coingecko.com/coins/images...,0.198642,1903425371,44,2928346724,4.487276e+07,0.202576,...,1.471117e+10,1.000000e+11,2.990000,-93.36082,2025-02-26T16:41:03.732Z,1.312440e-01,5.113305e+01,2026-02-11T17:06:46.605Z,None,2026-03-05T21:53:36.265Z
44,bittensor,tao,Bittensor,https://coin-images.coingecko.com/coins/images...,188.240000,1808455890,45,3957031447,9.926231e+07,193.420000,...,2.100000e+07,2.100000e+07,757.600000,-75.13094,2024-03-07T18:45:36.466Z,3.083000e+01,5.111236e+02,2023-05-14T08:57:53.732Z,None,2026-03-05T21:53:38.264Z
45,aave,aave,Aave,https://coin-images.coingecko.com/coins/images...,118.270000,1797159136,46,1893957346,3.742205e+08,119.470000,...,1.600000e+07,1.600000e+07,661.690000,-82.07254,2021-05-18T21:19:59.514Z,2.602000e+01,3.558412e+02,2020-11-05T09:20:11.928Z,None,2026-03-05T21:53:36.401Z
46,sky,sky,Sky,https://coin-images.coingecko.com/coins/images...,0.076915,1772002114,47,1804394112,2.595694e+07,0.078560,...,2.346267e+10,2.346267e+10,0.100535,-23.56264,2024-12-04T10:13:57.264Z,3.582727e-02,1.144916e+02,2025-02-03T05:01:48.626Z,None,2026-03-05T21:53:35.863Z
47,aster-2,aster,Aster,https://coin-images.coingecko.com/coins/images...,0.709325,1741425467,49,5549260866,2.034549e+08,0.759747,...,7.822985e+09,8.000000e+09,2.410000,-70.55198,2025-09-24T11:18:14.634Z,9.971300e-02,6.113633e+02,2025-09-17T12:05:36.771Z,None,2026-03-05T21:53:35.637Z
48,falcon-finance,usdf,Falcon USD,https://coin-images.coingecko.com/coins/images...,0.997526,1738015572,48,1738015572,1.537822e+06,0.998050,...,1.742220e+09,NaN,1.075000,-7.16975,2025-05-08T21:25:42.071Z,9.434220e-01,5.736050e+00,2025-07-08T10:16:34.749Z,None,2026-03-05T21:53:36.021Z
49,global-dollar,usdg,Global Dollar,https://coin-images.coingecko.com/coins/images...,0.999687,1708505691,50,1708505691,5.856218e+07,1.000000,...,1.709043e+09,NaN,1.650000,-39.57417,2025-01-30T00:11:05.728Z,9.075610e-01,1.015841e+01,2024-11-11T23:55:50.604Z,None,2026-03-05T21:53:40.007Z

In [164]:
#Primeras 5 filas
df5.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,71180.00,1425992334426,1,1425993404010,5.728301e+10,73476.00,...,1.999835e+07,2.100000e+07,126080.00,-43.54359,2025-10-06T18:57:42.558Z,67.810000,1.048716e+05,2013-07-06T00:00:00.000Z,None,2026-03-05T21:53:34.541Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2080.55,251453839190,2,251453839190,2.431761e+10,2162.46,...,1.206921e+08,NaN,4946.05,-57.93498,2025-08-24T19:21:03.333Z,0.432979,4.804214e+05,2015-10-20T00:00:00.000Z,"{'times': 38.08404353073514, 'currency': 'btc'...",2026-03-05T21:53:37.266Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.00,183911740439,3,189379070825,8.805857e+10,1.00,...,1.893655e+11,NaN,1.32,-24.41432,2018-07-24T00:00:00.000Z,0.572521,7.467841e+01,2015-03-02T00:00:00.000Z,None,2026-03-05T21:53:35.550Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,648.00,88438125292,4,88438125292,1.198932e+09,664.51,...,1.363585e+08,2.000000e+08,1369.99,-52.70029,2025-10-13T08:41:24.131Z,0.039818,1.627322e+06,2017-10-19T00:00:00.000Z,None,2026-03-05T21:53:34.429Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.41,85991929396,5,140741708202,2.787363e+09,1.45,...,9.998571e+10,1.000000e+11,3.65,-61.40524,2025-07-18T03:40:53.808Z,0.002686,5.229027e+04,2014-05-22T00:00:00.000Z,None,2026-03-05T21:53:35.322Z

In [165]:
#Últimas 10 filas
df5.tail(10)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
40,blackrock-usd-institutional-digital-liquidity-...,buidl,BlackRock USD Institutional Digital Liquidity ...,https://coin-images.coingecko.com/coins/images...,1.000000,2009494196,41,2006635146,0.0,1.000000,...,2.006635e+09,NaN,1.000000,0.00000,2025-02-12T05:00:10.912Z,1.000000,0.00000,2025-02-12T05:45:10.196Z,None,2026-03-05T21:50:23.212Z
41,hashnote-usyc,usyc,Circle USYC,https://coin-images.coingecko.com/coins/images...,1.120000,1946565991,42,1946565991,55935.0,1.120000,...,1.740028e+09,NaN,1.120000,-0.00027,2026-03-04T11:11:25.534Z,1.026000,9.02399,2024-12-05T22:31:20.475Z,None,2026-03-05T00:43:04.053Z
42,okb,okb,OKB,https://coin-images.coingecko.com/coins/images...,92.390000,1941874120,43,1941874120,349798146.0,117.600000,...,2.100000e+07,2.100000e+07,255.500000,-64.06221,2025-08-22T01:50:26.131Z,0.580608,15714.78387,2019-01-14T00:00:00.000Z,None,2026-03-05T21:53:38.102Z
43,pi-network,pi,Pi Network,https://coin-images.coingecko.com/coins/images...,0.198642,1903425371,44,2928346724,44872764.0,0.202576,...,1.471117e+10,1.000000e+11,2.990000,-93.36082,2025-02-26T16:41:03.732Z,0.131244,51.13305,2026-02-11T17:06:46.605Z,None,2026-03-05T21:53:36.265Z
44,bittensor,tao,Bittensor,https://coin-images.coingecko.com/coins/images...,188.240000,1808455890,45,3957031447,99262306.0,193.420000,...,2.100000e+07,2.100000e+07,757.600000,-75.13094,2024-03-07T18:45:36.466Z,30.830000,511.12357,2023-05-14T08:57:53.732Z,None,2026-03-05T21:53:38.264Z
45,aave,aave,Aave,https://coin-images.coingecko.com/coins/images...,118.270000,1797159136,46,1893957346,374220463.0,119.470000,...,1.600000e+07,1.600000e+07,661.690000,-82.07254,2021-05-18T21:19:59.514Z,26.020000,355.84122,2020-11-05T09:20:11.928Z,None,2026-03-05T21:53:36.401Z
46,sky,sky,Sky,https://coin-images.coingecko.com/coins/images...,0.076915,1772002114,47,1804394112,25956937.0,0.078560,...,2.346267e+10,2.346267e+10,0.100535,-23.56264,2024-12-04T10:13:57.264Z,0.035827,114.49158,2025-02-03T05:01:48.626Z,None,2026-03-05T21:53:35.863Z
47,aster-2,aster,Aster,https://coin-images.coingecko.com/coins/images...,0.709325,1741425467,49,5549260866,203454913.0,0.759747,...,7.822985e+09,8.000000e+09,2.410000,-70.55198,2025-09-24T11:18:14.634Z,0.099713,611.36326,2025-09-17T12:05:36.771Z,None,2026-03-05T21:53:35.637Z
48,falcon-finance,usdf,Falcon USD,https://coin-images.coingecko.com/coins/images...,0.997526,1738015572,48,1738015572,1537822.0,0.998050,...,1.742220e+09,NaN,1.075000,-7.16975,2025-05-08T21:25:42.071Z,0.943422,5.73605,2025-07-08T10:16:34.749Z,None,2026-03-05T21:53:36.021Z
49,global-dollar,usdg,Global Dollar,https://coin-images.coingecko.com/coins/images...,0.999687,1708505691,50,1708505691,58562175.0,1.000000,...,1.709043e+09,NaN,1.650000,-39.57417,2025-01-30T00:11:05.728Z,0.907561,10.15841,2024-11-11T23:55:50.604Z,None,2026-03-05T21:53:40.007Z

In [169]:
#Muestre la fila 2 a la 5 y solamente la segunda columna
df5.iloc[1:5, 1]

1     eth
2    usdt
3     bnb
4     xrp
Name: symbol, dtype: object

In [167]:
#Use .len() para saber cuantas filas tiene
len(df5)

50

In [170]:
#Use .shape para saber el numero de filas y columnas
df5.shape

(50, 26)

In [171]:
#Use .columns para ver el nombre de las columnas
df5.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='object')

In [172]:
#Use .dtypes para saber el tipo de dato de cada columna
df5.dtypes

id                                   object
symbol                               object
name                                 object
image                                object
current_price                       float64
market_cap                            int64
market_cap_rank                       int64
fully_diluted_valuation               int64
total_volume                        float64
high_24h                            float64
low_24h                             float64
price_change_24h                    float64
price_change_percentage_24h         float64
market_cap_change_24h               float64
market_cap_change_percentage_24h    float64
circulating_supply                  float64
total_supply                        float64
max_supply                          float64
ath                                 float64
ath_change_percentage               float64
ath_date                             object
atl                                 float64
atl_change_percentage               float64
atl_date                             object
roi                                  object
last_updated                         object
dtype: object

In [173]:
#Use .info() para ver toda la información del conjunto de datos (número de filas, columnas, nombre de columnas, tipos de datos y si hay valores nulos)
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                50 non-null     object
 1   symbol                            50 non-null     object
 2   name                              50 non-null     object
 3   image                             50 non-null     object
 4   current_price                     50 non-null     float64
 5   market_cap                        50 non-null     int64
 6   market_cap_rank                   50 non-null     int64
 7   fully_diluted_valuation           50 non-null     int64
 8   total_volume                      50 non-null     float64
 9   high_24h                          50 non-null     float64
 10  low_24h                           50 non-null     float64
 11  price_change_24h                  50 non-null     float64
 12  price_change_percentage_24h       50 non-null     float64
 13  market_cap_change_24h             50 non-null     float64
 14  market_cap_change_percentage_24h  50 non-null     float64
 15  circulating_supply                50 non-null     float64
 16  total_supply                      50 non-null     float64
 17  max_supply                        26 non-null     float64
 18  ath                               50 non-null     float64
 19  ath_change_percentage             50 non-null     float64
 20  ath_date                          50 non-null     object
 21  atl                               50 non-null     float64
 22  atl_change_percentage             50 non-null     float64
 23  atl_date                          50 non-null     object
 24  roi                               2 non-null      object
 25  last_updated                      50 non-null     object
dtypes: float64(15), int64(3), object(8)
memory usage: 10.3+ KB